// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvhhmrgzfkbcwgplejpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2aGhtcmd6ZmtiY3dncGxlanBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NTExMzksImV4cCI6MjA2NzMyNzEzOX0.lSyDo5Ky6VXVYHQ4ZRcbKOxHhKO-OhfsNhR1f0rwM_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});